=== MarkoMoravcik/SIPVS-CV/src/main/resources/biography_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="biography">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element type="xsd:dateTime" name="date_created" minOccurs="1" maxOccurs="1" />
        <xsd:element type="xsd:string" name="place" minOccurs="1" maxOccurs="1" />
        <xsd:element name="personal_info">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element type="xsd:string" name="title_before" minOccurs="0" maxOccurs="1" />
              <xsd:element type="xsd:string" name="first_name" minOccurs="1" maxOccurs="1" />
              <xsd:element type="xsd:string" name="surname" minOccurs="1" maxOccurs="1" />
              <xsd:element type="xsd:date" name="birth_date" minOccurs="1" maxOccurs="1" />
              <xsd:element type="xsd:string" name="title_after" minOccurs="0" maxOccurs="1" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="contact_info" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element type="xsd:string" name="email" minOccurs="1" maxOccurs="1" />
              <xsd:element type="xsd:string" name="phone" minOccurs="1" maxOccurs="1" />
              <xsd:element name="address">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="country" minOccurs="0" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="city" minOccurs="0" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="street" minOccurs="0" maxOccurs="1" />
                    <xsd:element type="xsd:integer" name="postal_code" minOccurs="0" maxOccurs="1" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="education" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="school" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="name" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="faculty" minOccurs="0" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="profession" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="degree_type" name="degree" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:date" name="start_date" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:date" name="end_date" minOccurs="0" maxOccurs="1" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="courses" minOccurs="0" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="course" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="organization" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="name" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="valid_from" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="valid_to" minOccurs="0" maxOccurs="1" />
                  </xsd:sequence>
                  <xsd:attribute type="xsd:integer" name="type" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="career" minOccurs="0" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="experience" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="employer" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="profession" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="description" minOccurs="0" maxOccurs="1" />
                    <xsd:element type="xsd:date" name="start_date" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:date" name="end_date" minOccurs="0" maxOccurs="1" />
                    <xsd:element name="projects">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="project" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element type="xsd:string" name="name" minOccurs="1" maxOccurs="1" />
                                <xsd:element type="xsd:string" name="description" minOccurs="1" maxOccurs="1" />
                                <xsd:element type="xsd:string" name="role" minOccurs="1" maxOccurs="1" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="skills" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="skill" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="name" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="skill_level_type" name="level" minOccurs="1" maxOccurs="1" />
                    <xsd:element type="xsd:string" name="years" minOccurs="1" maxOccurs="1" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="degree_type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="isced_2011_1" />
      <xsd:enumeration value="isced_2011_2" />
      <xsd:enumeration value="isced_2011_3" />
      <xsd:enumeration value="isced_2011_4" />
      <xsd:enumeration value="isced_2011_5" />
      <xsd:enumeration value="isced_2011_6" />
      <xsd:enumeration value="isced_2011_7" />
      <xsd:enumeration value="isced_2011_8" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="skill_level_type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="beginner" />
      <xsd:enumeration value="intermediate" />
      <xsd:enumeration value="expert" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== MarkoMoravcik/SIPVS-CV/valid_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<biography xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biography_schema.xsd">
  <date_created>2015-09-10T09:24:32</date_created>
  <place>Bratislava</place>
  <personal_info>
  	<title_before>Ing.</title_before>
    <first_name>Branislav</first_name>
    <surname>Široký</surname>
    <title_after>PhD.</title_after>
    <birth_date>3/4/2011</birth_date>
  </personal_info>
  <contact_info>
    <email>branislav@siroky.sk</email>
    <phone>+421 903 940 397</phone>
    <address>
      <country>Slovakia</country>
      <city>Bratislava</city>
      <street>Ilkovičova 2</street>
      <postal_code>84104</postal_code>
    </address>
  </contact_info>
  <education>
    <school>
      <name>Slovenská Technická Univerzita</name>
      <faculty>Fakulta Elektrotechniky a Informatiky</faculty>
      <profession>Aplikovaná Informatika</profession>
      <degree>isced_2011_7</degree>
      <start_date>1990-09-21</start_date>
      <end_date>1995-06-30</end_date>
    </school>
  </education>
  <courses>
    <!-- type: 0 == course, 1 == certificate -->
    <course type="0">
      <organization>Tunelárska elektrika, spol. s r.o.</organization>
      <name>Elektrotechnická spôsobilosť §22</name>
      <valid_from>2010-02-27</valid_from>
      <valid_to>2015-02-27</valid_to>
    </course>
    <course type="1">
      <organization>CISCO Network Academy</organization>
      <name>CCNP</name>
      <valid_from>2013-02-27</valid_from>
    </course>
  </courses>
  <career>
    <experience>
      <employer>Fakulta Informatiky a Informačných technológií</employer>
      <profession>Systémová administrácia</profession>
      <description>man bash</description>
      <start_date>1996-07-30</start_date>
      <projects>
        <project>
          <name>Digitálna FIIT</name>
          <description>curl XGET http://fiit.stuba.sk</description>
          <role>Decision maker</role>
        </project>
      </projects>
    </experience>
  </career>
  <skills>
    <skill>
      <name>Bash</name>
      <level>expert</level>
      <years>28</years>
    </skill>
    <skill>
      <name>C</name>
      <level>expert</level>
      <years>22</years>
    </skill>
    <skill>
      <name>C#</name>
      <level>beginner</level>
      <years>2</years>
    </skill>
  </skills>
</biography>
